import { StyleSheet, Dimensions, Platform } from 'react-native';
import { Spacing, BorderRadius, Shadows, Typography } from '@/constants/DesignSystem';
import { colors } from '@/constants/theme';

const { width } = Dimensions.get('window');

export const earnStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing['4xl'],
    paddingBottom: Spacing.base,
    backgroundColor: colors.background.primary,
    borderBottomWidth: 1,
    borderBottomColor: colors.slateLight,
  },
  headerTitle: {
    ...Typography.h2,
    color: colors.nileBlue,
    marginBottom: Spacing.base,
    fontFamily: 'Poppins',
  },
  walletGrid: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  walletCard: {
    flex: 1,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  walletLabel: {
    fontSize: 11,
    color: '#4A5568',
    marginBottom: Spacing.xs,
    fontWeight: '500',
  },
  walletValue: {
    ...Typography.h3,
    fontWeight: 'bold',
  },
  monthlyCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: '#80DFAD',
  },
  monthlyLabel: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
    marginBottom: Spacing.xs,
  },
  monthlyValue: {
    ...Typography.h2,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  monthlyButtons: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  walletButton: {
    backgroundColor: colors.gold,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  walletButtonText: {
    ...Typography.bodySmall,
    color: colors.nileBlue,
    fontWeight: '600',
  },
  howButton: {
    backgroundColor: '#EDF2F7',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
  },
  howButtonText: {
    ...Typography.bodySmall,
    color: colors.nileBlue,
    fontWeight: '600',
  },
  section: {
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.base,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  sectionHeaderWithLink: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Spacing.base,
  },
  sectionTitle: {
    ...Typography.h3,
    color: colors.nileBlue,
    fontFamily: 'Poppins',
  },
  sectionSubtitle: {
    fontSize: 11,
    color: '#4A5568',
    marginTop: Spacing.xs,
    marginBottom: Spacing.md,
  },
  viewAllLink: {
    ...Typography.bodySmall,
    color: colors.gold,
  },
  quickEarnGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  quickEarnCard: {
    width: (width - 44) / 2,
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.slateLight,
    ...Shadows.medium,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: BorderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  quickEarnTitle: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.nileBlue,
    marginBottom: Spacing.xs,
  },
  quickEarnReward: {
    fontSize: 11,
    color: '#00A85D',
    fontWeight: '500',
  },
  socialMediaBanner: {
    marginHorizontal: Spacing.base,
    marginBottom: Spacing.lg,
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
  },
  socialMediaGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.base,
    paddingHorizontal: 18,
  },
  socialMediaLeft: {
    flex: 1,
  },
  socialMediaIconRow: {
    flexDirection: 'row',
    marginBottom: Spacing.sm,
  },
  socialMediaIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialMediaTitle: {
    ...Typography.bodyLarge,
    fontWeight: '800',
    color: colors.text.inverse,
    marginBottom: 2,
  },
  socialMediaSubtitle: {
    ...Typography.bodySmall,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '500',
  },
  socialMediaArrow: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  creatorSection: {
    marginHorizontal: Spacing.base,
    marginVertical: Spacing.base,
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
  },
  creatorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.base,
  },
  creatorIcon: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.xl,
    justifyContent: 'center',
    alignItems: 'center',
  },
  creatorHeaderText: {
    flex: 1,
    marginLeft: Spacing.md,
  },
  creatorTitle: {
    ...Typography.bodyLarge,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  creatorSubtitle: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
  },
  exploreLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  exploreLinkText: {
    ...Typography.bodySmall,
    color: colors.brand.purpleMedium,
    fontWeight: '600',
  },
  creatorCTA: {
    borderRadius: BorderRadius.md,
    overflow: 'hidden',
  },
  creatorCTAGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
  },
  creatorCTAText: {
    ...Typography.body,
    color: colors.text.inverse,
    fontWeight: '600',
  },
  featuredCreatorsGrid: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.base,
  },
  creatorCard: {
    flex: 1,
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  creatorAvatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  creatorAvatar: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.xl,
  },
  verifiedBadge: {
    marginLeft: Spacing.xs,
  },
  creatorName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: Spacing.xs,
  },
  creatorStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  creatorStatText: {
    fontSize: 11,
    color: colors.text.tertiary,
  },
  creatorStatDivider: {
    fontSize: 11,
    color: colors.text.tertiary,
  },
  trendingSection: {
    marginBottom: Spacing.base,
  },
  trendingTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: Spacing.md,
  },
  trendingScroll: {
    marginHorizontal: -Spacing.base,
    paddingHorizontal: Spacing.base,
  },
  pickCard: {
    width: 140,
    marginRight: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: colors.background.primary,
    overflow: 'hidden',
    ...Shadows.medium,
  },
  pickImageContainer: {
    width: '100%',
    aspectRatio: 1,
    position: 'relative',
  },
  pickImage: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: BorderRadius.md,
    borderTopRightRadius: BorderRadius.md,
  },
  pickHeartButton: {
    position: 'absolute',
    top: Spacing.sm,
    right: Spacing.sm,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickTag: {
    position: 'absolute',
    top: Spacing.sm,
    left: Spacing.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  pickTagText: {
    ...Typography.overline,
    fontWeight: '600',
    color: colors.text.inverse,
    textTransform: undefined,
    letterSpacing: undefined,
  },
  pickVideoBadge: {
    position: 'absolute',
    bottom: Spacing.sm,
    left: Spacing.sm,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 4,
    padding: 3,
  },
  pickViewsBadge: {
    position: 'absolute',
    bottom: Spacing.sm,
    right: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  pickViewsText: {
    ...Typography.overline,
    fontWeight: '600',
    color: colors.text.primary,
    textTransform: undefined,
    letterSpacing: undefined,
  },
  pickContent: {
    padding: 10,
  },
  pickTitle: {
    ...Typography.bodySmall,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: Spacing.xs,
  },
  pickPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    marginBottom: Spacing.xs,
  },
  pickPrice: {
    ...Typography.body,
    fontWeight: '700',
    color: colors.text.primary,
  },
  pickBrand: {
    fontSize: 10,
    color: colors.text.tertiary,
  },
  pickStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  pickStatText: {
    fontSize: 10,
    color: colors.text.tertiary,
  },
  pickStatDivider: {
    fontSize: 10,
    color: colors.neutral[300],
  },
  streakCard: {
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  streakHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.base,
  },
  streakIconContainer: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(249,115,22,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.md,
  },
  streakTitle: {
    ...Typography.h4,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  streakSubtitle: {
    ...Typography.body,
    color: colors.text.tertiary,
  },
  streakMilestones: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: Spacing.sm,
  },
  milestoneItem: {
    flex: 1,
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.slateLight,
    alignItems: 'center',
  },
  milestoneCompleted: {
    backgroundColor: colors.tint.orange,
    borderColor: '#FED7AA',
  },
  milestoneDay: {
    fontSize: 10,
    color: colors.text.tertiary,
    marginBottom: Spacing.xs,
  },
  milestoneCoins: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.text.tertiary,
  },
  milestoneCoinsCompleted: {
    color: colors.brand.orange,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: colors.slateLight,
    borderRadius: 4,
    marginBottom: Spacing.base,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.brand.orange,
  },
  checkinButton: {
    borderRadius: BorderRadius.md,
    overflow: 'hidden',
  },
  checkinGradient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
  },
  checkinText: {
    ...Typography.body,
    color: colors.text.inverse,
    fontWeight: '600',
  },
  shoppingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.slateLight,
    marginBottom: Spacing.md,
  },
  shoppingIconContainer: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(0,192,106,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.base,
  },
  shoppingContent: {
    flex: 1,
  },
  shoppingTitle: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.nileBlue,
    marginBottom: Spacing.xs,
  },
  shoppingDescription: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
    marginBottom: Spacing.sm,
  },
  shoppingRewards: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  shoppingReward: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.brand.amberDeep,
  },
  shoppingExtra: {
    ...Typography.bodySmall,
    color: colors.brand.purpleMedium,
  },
  highlightCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: '#C0F0D9',
  },
  highlightText: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.nileBlue,
  },
  socialGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  socialCard: {
    width: (width - 44) / 2,
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.slateLight,
  },
  socialTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.nileBlue,
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
  },
  socialDescription: {
    fontSize: 11,
    color: colors.text.tertiary,
    marginBottom: Spacing.sm,
  },
  socialCoins: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.brand.pink,
  },
  socialHighlight: {
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.base,
    borderWidth: 1,
    borderColor: '#FBCFE8',
  },
  socialHighlightText: {
    ...Typography.body,
    color: colors.nileBlue,
    textAlign: 'center',
  },
  socialHighlightBold: {
    fontWeight: '600',
  },
  impactCard: {
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
  },
  impactGradient: {
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  impactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.base,
  },
  impactIcon: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  impactHeaderText: {
    flex: 1,
    marginLeft: Spacing.md,
  },
  impactTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  impactTitle: {
    ...Typography.h4,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  impactBadge: {
    backgroundColor: 'rgba(255,205,87,0.2)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.md,
  },
  impactBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.gold,
  },
  impactSubtitle: {
    ...Typography.body,
    color: colors.text.tertiary,
  },
  impactActivities: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  impactActivity: {
    flex: 1,
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    backgroundColor: colors.background.primary,
    alignItems: 'center',
  },
  impactActivityIcon: {
    fontSize: 24,
    marginBottom: Spacing.xs,
  },
  impactActivityLabel: {
    fontSize: 10,
    color: colors.text.tertiary,
    marginBottom: Spacing.xs,
    textAlign: 'center',
  },
  impactActivityCoins: {
    ...Typography.bodySmall,
    fontWeight: 'bold',
    color: colors.gold,
  },
  impactFooter: {
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
  },
  impactFooterText: {
    ...Typography.body,
    color: colors.nileBlue,
    textAlign: 'center',
  },
  programCard: {
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.slateLight,
    marginBottom: Spacing.md,
  },
  programHeader: {
    flexDirection: 'row',
    marginBottom: Spacing.md,
  },
  programIconContainer: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(245,158,11,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.base,
  },
  programContent: {
    flex: 1,
  },
  programTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  programTitle: {
    ...Typography.bodyLarge,
    fontWeight: '600',
    color: colors.nileBlue,
  },
  programBadge: {
    ...Typography.h3,
  },
  programRewards: {
    marginBottom: Spacing.sm,
  },
  programRewardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  programRewardText: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
  },
  programEarnings: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.warning,
  },
  eligibilityButton: {
    backgroundColor: colors.background.secondary,
    paddingVertical: 10,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
  },
  eligibilityButtonActive: {
    backgroundColor: colors.tint.greenLight,
  },
  eligibilityButtonSuspended: {
    backgroundColor: colors.errorScale[50],
  },
  eligibilityText: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.nileBlue,
  },
  eligibilityTextActive: {
    color: colors.success,
  },
  eligibilityTextSuspended: {
    color: colors.error,
  },
  eventsCard: {
    borderRadius: BorderRadius.lg,
    overflow: 'hidden',
  },
  eventsGradient: {
    padding: Spacing.lg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: '#E9D5FF',
  },
  eventsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.base,
  },
  eventsIconContainer: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(168,85,247,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.md,
  },
  eventsHeaderText: {
    flex: 1,
  },
  eventsTitle: {
    ...Typography.h4,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  eventsSubtitle: {
    ...Typography.body,
    color: colors.text.tertiary,
  },
  eventsTypes: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.base,
  },
  eventType: {
    flex: 1,
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    backgroundColor: colors.background.secondary,
    alignItems: 'center',
  },
  eventTypeIcon: {
    fontSize: 24,
    marginBottom: Spacing.xs,
  },
  eventTypeLabel: {
    fontSize: 10,
    color: colors.text.tertiary,
  },
  eventsFooter: {
    padding: Spacing.md,
    borderRadius: BorderRadius.sm,
    backgroundColor: colors.background.secondary,
  },
  eventsFooterText: {
    ...Typography.body,
    color: colors.nileBlue,
  },
  bonusCard: {
    flexDirection: 'row',
    padding: Spacing.lg,
    borderRadius: BorderRadius.md,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: '#FED7AA',
    marginBottom: Spacing.md,
  },
  bonusIconContainer: {
    width: 48,
    height: 48,
    borderRadius: BorderRadius.md,
    backgroundColor: 'rgba(249,115,22,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.base,
  },
  bonusContent: {
    flex: 1,
  },
  bonusTitle: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.nileBlue,
    marginBottom: Spacing.xs,
  },
  bonusDescription: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
    marginBottom: Spacing.sm,
  },
  bonusFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bonusReward: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.gold,
  },
  bonusTime: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  bonusTimeText: {
    ...Typography.bodySmall,
    fontWeight: '600',
    color: colors.brand.orange,
  },
  gamesIconBg: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.nileBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gamesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  gameCardOuter: {
    width: (width - 42) / 2,
  },
  gameCard: {
    padding: 14,
    borderRadius: BorderRadius.lg,
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.tint.slate,
    ...Platform.select({
      ios: {
        shadowColor: colors.nileBlue,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: { elevation: 2 },
      web: { boxShadow: '0px 2px 8px rgba(26,58,82,0.06)' },
    }),
  },
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  gameIconCircle: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gameIcon: {
    fontSize: 22,
  },
  gameCoinsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: 10,
  },
  gameCoinsText: {
    fontSize: 11,
    fontWeight: '700',
  },
  gameTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.nileBlue,
    marginBottom: 6,
  },
  gamePlaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.xs,
  },
  gamePlaysLabel: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '500',
  },
  gameProgressBarBg: {
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.tint.slate,
    overflow: 'hidden',
  },
  gameProgressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  gameTodayEarnings: {
    fontSize: 10,
    fontWeight: '600',
    marginTop: 6,
  },
  challengeCard: {
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
    backgroundColor: colors.background.secondary,
    borderWidth: 1,
    borderColor: colors.slateLight,
    marginBottom: Spacing.md,
  },
  challengeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  challengeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  challengeIcon: {
    fontSize: 24,
  },
  challengeTitle: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.nileBlue,
  },
  challengeTime: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
  },
  challengeReward: {
    alignItems: 'flex-end',
  },
  challengeCoins: {
    ...Typography.bodySmall,
    fontWeight: 'bold',
    color: colors.warning,
  },
  challengeProgress: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
  },
  challengeProgressBar: {
    height: 6,
    backgroundColor: colors.slateLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  challengeProgressFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: colors.gold,
  },
  tournamentIconBg: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.warning,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tournamentLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.errorScale[50],
    paddingHorizontal: 10,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  tournamentLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.error,
  },
  tournamentLiveText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.error,
    letterSpacing: 0.5,
  },
  tournamentCard: {
    padding: Spacing.base,
    borderRadius: 18,
    overflow: 'hidden',
    position: 'relative',
  },
  tournamentStatusBadge: {
    position: 'absolute',
    top: Spacing.md,
    right: Spacing.md,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.sm,
  },
  tournamentStatusText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.text.inverse,
    letterSpacing: 0.5,
  },
  tournamentTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: 14,
  },
  tournamentIcon: {
    fontSize: 32,
  },
  tournamentTitle: {
    ...Typography.bodyLarge,
    fontWeight: '700',
    color: colors.text.inverse,
    marginBottom: 2,
  },
  tournamentPlayersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  tournamentParticipants: {
    ...Typography.bodySmall,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '500',
  },
  tournamentStatsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: BorderRadius.md,
    padding: 10,
    marginBottom: Spacing.md,
  },
  tournamentStatBox: {
    flex: 1,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  tournamentStatBoxMiddle: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  tournamentStatBoxValue: {
    ...Typography.body,
    fontWeight: '700',
    color: colors.text.inverse,
  },
  tournamentStatBoxLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.5)',
    fontWeight: '500',
  },
  tournamentCTA: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: colors.gold,
    borderRadius: 10,
    paddingVertical: 10,
  },
  tournamentCTAText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.nileBlue,
  },
  tournamentEmptyCard: {
    alignItems: 'center',
    paddingVertical: Spacing['2xl'],
    paddingHorizontal: Spacing.lg,
    backgroundColor: colors.tint.coolGray,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.slateLight,
    borderStyle: 'dashed',
  },
  tournamentEmptyTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.slateGray,
    marginTop: 10,
    marginBottom: Spacing.xs,
  },
  tournamentEmptyText: {
    ...Typography.bodySmall,
    color: '#94A3B8',
    textAlign: 'center',
  },
  achievementsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  achievementCard: {
    width: (width - 44) / 2,
    padding: Spacing.base,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  achievementUnlocked: {
    backgroundColor: 'rgba(245,158,11,0.15)',
    borderColor: 'rgba(245,158,11,0.3)',
  },
  achievementLocked: {
    backgroundColor: colors.background.secondary,
    borderColor: colors.slateLight,
    opacity: 0.6,
  },
  achievementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  achievementIcon: {
    fontSize: 32,
  },
  achievementTitle: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.nileBlue,
    marginBottom: Spacing.xs,
  },
  achievementCoins: {
    ...Typography.bodySmall,
    fontWeight: '600',
    color: colors.warning,
  },
  achievementProgressContainer: {
    marginTop: Spacing.sm,
  },
  achievementProgressBar: {
    height: 4,
    backgroundColor: colors.slateLight,
    borderRadius: 2,
    overflow: 'hidden',
  },
  achievementProgressFill: {
    height: '100%',
    backgroundColor: colors.gold,
    borderRadius: 2,
  },
  achievementProgressText: {
    fontSize: 10,
    color: colors.text.tertiary,
    marginTop: Spacing.xs,
  },
  leaderboardCard: {
    padding: Spacing.xl,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.infoScale[200],
    alignItems: 'center',
  },
  leaderboardTitle: {
    ...Typography.h4,
    fontWeight: 'bold',
    color: colors.nileBlue,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  leaderboardText: {
    ...Typography.body,
    color: colors.text.tertiary,
    textAlign: 'center',
    marginBottom: Spacing.base,
  },
  leaderboardButton: {
    borderRadius: BorderRadius['2xl'],
    overflow: 'hidden',
  },
  leaderboardButtonGradient: {
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
  },
  leaderboardButtonText: {
    ...Typography.body,
    fontWeight: '600',
    color: colors.text.inverse,
  },
  whyRezCard: {
    padding: Spacing.base,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: colors.border.default,
    backgroundColor: colors.background.primary,
    ...Shadows.subtle,
  },
  whyRezTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: colors.text.primary,
    textAlign: 'center',
    marginBottom: Spacing.base,
  },
  whyRezGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  whyRezItem: {
    width: '48%',
    paddingVertical: Spacing.base,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: colors.tint.purpleLight,
    alignItems: 'center',
    marginBottom: 2,
  },
  whyRezEmoji: {
    fontSize: 32,
    marginBottom: 10,
  },
  whyRezItemTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: Spacing.xs,
    textAlign: 'center',
  },
  whyRezItemSubtitle: {
    fontSize: 11,
    color: colors.text.tertiary,
    textAlign: 'center',
    lineHeight: 15,
  },
  bottomCTA: {
    position: 'absolute',
    bottom: 80,
    left: Spacing.base,
    right: Spacing.base,
  },
  bottomCTAGradient: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
  },
  bottomCTAContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  bottomCTATitle: {
    ...Typography.body,
    fontWeight: 'bold',
    color: colors.text.inverse,
  },
  bottomCTASubtitle: {
    ...Typography.bodySmall,
    color: 'rgba(255,255,255,0.9)',
  },
  emptySection: {
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.secondary,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.md,
  },
  emptySectionText: {
    ...Typography.body,
    color: colors.text.tertiary,
    textAlign: 'center',
  },
  bonusOppCard: {
    backgroundColor: colors.background.primary,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.background.secondary,
    ...Shadows.subtle,
  },
  bonusOppRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
  },
  bonusOppIcon: {
    fontSize: 24,
  },
  bonusOppTitle: {
    ...Typography.body,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 2,
  },
  bonusOppDesc: {
    ...Typography.bodySmall,
    color: colors.text.tertiary,
  },
  bonusOppRight: {
    alignItems: 'flex-end',
    gap: Spacing.xs,
  },
  bonusOppReward: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.success,
  },
  bonusOppTimeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: colors.background.secondary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.sm,
  },
  bonusOppUrgent: {
    backgroundColor: colors.errorScale[100],
  },
  bonusOppTime: {
    fontSize: 10,
    color: colors.text.tertiary,
    fontWeight: '600',
  },
});
