name: Runner Test

on:
  push:
    branches: [debug/ci-workflow-dispatch]
  workflow_dispatch:

jobs:
  test:
    name: Runner Test
    runs-on: ubuntu-22.04
    steps:
      - name: Echo
        run: echo "Hello World"
